### Add new message
POST /api/messages/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Host: localhost:5004

{
  "content": "Hello 3",
  "conversationId": "{{convMihDim}}"
}

### Get all messages for conv
GET /api/messages/{{convMihDim}} HTTP/1.1
Authorization: Bearer {{token}}
Host: localhost:5004

### Edit message
PUT /api/messages/edit HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
Host: localhost:5004

{
  "messageId": "187ea9c5-6a8d-4514-ba8c-1fa8e7d47033",
  "newContent": "222222bbbbbb"
}

### Delete message
DELETE /api/messages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
Host: localhost:5004

{
  "messageId": "187ea9c5-6a8d-4514-ba8c-1fa8e7d47033",
  "newContent": "222222bbbbbb"
}

### Read the message
POST /api/messages/1429a6fc-dfed-4755-a07b-206705848c8e/read HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Host: localhost:5004

{
  "content": "Hello 2",
  "conversationId": "{{convMihDim}}"
}
