### Add reaction
POST /api/Messages/reaction HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
Host: localhost:5004

{
  "messageId": "9acdf1bd-fcc0-46f9-ae74-4a631a152361",
  "reactionId": "3"
}

<> 2025-06-15T141226.200.json


### Add different reaction to the same message
POST /api/Messages/reaction HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
Host: localhost:5004

{
  "messageId": "9acdf1bd-fcc0-46f9-ae74-4a631a152361",
  "reactionId": "1"
}


### Delete reaction
DELETE /api/messages/reactions/9acdf1bd-fcc0-46f9-ae74-4a631a152361/2
Content-Type: application/json
Authorization: Bearer {{token}}
Host: localhost:5004


### Get all message reactions
GET /api/messages/reactions/9acdf1bd-fcc0-46f9-ae74-4a631a152361 HTTP/1.1
Authorization: Bearer {{token}}
Host: localhost:5004

